//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vvuelos_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivo
    {
        public int Codigo { get; set; }
        public int ClaseID { get; set; }
        public bool TienePrefijo { get; set; }
        public string Prefijo { get; set; }
        public bool TieneRango { get; set; }
        public int RangoInicial { get; set; }
        public int RangoFinal { get; set; }
        public int Actual { get; set; }
    
        public virtual Clase Clase { get; set; }
    }
}
