//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vvuelospago_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyPay
    {
        public int Num_Cuenta { get; set; }
        public int Codigo_Seguridad { get; set; }
        public string Contrasena { get; set; }
    }
}
