//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vvuelospago_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public long Num_Tarjeta { get; set; }
        public int Mes_Exp { get; set; }
        public int Ano_Exp { get; set; }
        public int CVV { get; set; }
        public decimal Monto { get; set; }
        public string Tipo { get; set; }
    }
}
